### ISSUE TITLE
Executing script

### ISSUE THREAD

**Issue by yash-gamooga** [SymmetricInfinity/push_package#16]
Please clarify on how to use the script. I get 

Usage: push_package [options]

along with options when i execute with all the options already present. Please help

**Comment by adamvduke** [comment]
Can you show what you've already tried? It's difficult to help without more information.

The script exits with a status code of 1 and prints the usage in two places.
https://github.com/SymmetricInfinity/push_package/blob/b45ba92ab9f5d380366d1d740a801c1a88c7e644/bin/push_package#L41
https://github.com/SymmetricInfinity/push_package/blob/b45ba92ab9f5d380366d1d740a801c1a88c7e644/bin/push_package#L48

It is either detecting that the `--website-json` or `--certificate` options are not files, or the `iconset-path` is not a directory.

Example usage:
`push_package --website-json=./website.json --iconset=~/project/iconset --certificate=./Certificate.p12 --output-dir=./`

**Comment by yash-gamooga** [comment]
push_package --website-json=./website.json --iconset=~/project/iconset/ --certificate=../../latest_cer.p12 --password=xxxxxxxxx --intermediate-certificate=latest_cer.cer --output-dir=./

I used this. The paths are correct.

**Comment by adamvduke** [comment]
The second flag you are using should be `--iconset-path` whereas your examples have `--iconset`.

The example usage was incorrect.

**Comment by yash-gamooga** [comment]
Sorry to trouble you again but that gives me the same output. Its not reading the arguments at all. The output is same as when you just type push_package

**Comment by adamvduke** [comment]
It's possible that the relative paths are not working correctly. I made a small change yesterday to attempt to expand the paths and print better output about which files the script can't find if it fails. I would recommend using fully qualified paths and/or updating to the 0.5.1 release.
