### ISSUE TITLE
"header too long" when use Apple intermediate cert 

### ISSUE THREAD

**Issue by eugenemelnikov** [SymmetricInfinity/push_package#8]
When generating push package with Apple intermediate cert, it throws error "header too long".

When generating push package without Apple intermediate cert, it works normal.

**Comment by adamvduke** [comment]
@eugenemelnikov can you include the entire stack trace?

**Comment by eugenemelnikov** [comment]
Already figured out. The thing was in apple intermediate certificate, that been corrupted. Re-download certificate from Apple solved this. My bad, sorry.

**Comment by adamvduke** [comment]
Thanks for the follow up. Going to close this.
