### ISSUE TITLE
how to pass intermediate apple WWDR certificate as command line option?

### ISSUE THREAD

**Issue by KCastiglione** [SymmetricInfinity/push_package#9]
$> push_package --website-json=./website.json --iconset-path=~/project/iconset --output-dir=./ --certificate=./Certificate.p12 --intermediate_cert=~/Downloads/AppleWWDRCA.cer

     /usr/local/lib/ruby/gems/2.3.0/gems/push_package-0.2.0/bin/push_package:29:in `<top (required)>': invalid option: --intermediate_cert=~/Downloads/AppleWWDRCA.cer (OptionParser::InvalidOption)
	from /usr/local/bin/push_package:23:in `load'

**Comment by adamvduke** [comment]
@KCastiglione nice catch! I just added the following CLI options and pushed a new version. https://rubygems.org/gems/push_package/versions/0.3.0

```
-I/--intermediate-certificate
-p/--password
```

**Comment by KCastiglione** [comment]
@adamvduke thank you for the quick fix! push_package is great!
